### ISSUE TITLE
No connection?

### ISSUE THREAD

**Issue by flipse-gege** [Alex9779/node-red-contrib-raumfeld#10]
Hi Alex,

Thanks for your great work - it's been going great so far! Recently, the control no longer works - was there an update of Teufel or is it just me? So far as I know, I have not changed anything in my configuration...

Greetings

**Comment by Alex9779** [comment]
No idea, for me it still works despite some problems pausing if streamed from Spotify I have no issues so far...

**Comment by Alex9779** [comment]
Just for info, I don't find any new updates, my speakers run on 2.17.4

**Comment by flipse-gege** [comment]
ok, good to know! Then the problem is probably with me - as so often :) Thanks!
