### ISSUE TITLE
Zone erstellen

### ISSUE THREAD

**Issue by Dexxter23** [Alex9779/node-red-contrib-raumfeld#11]
Hallo,
ich habe hier die Raumfeld Nodes die so wunderbar funktionieren.
Auch die " Drop from Zone " Node macht was sie soll.
Jetzt die Frage, wie füge ich Lautsprecher zu einer Zone hinzu?

**Comment by Alex9779** [comment]
Hi,
das passiert eigentlich automatisch, wenn du ein Abspielkommando wie 'load-playlist' oder 'load-favorite' mit einer Liste an Räumen ausführst bzw. kann über 'Group rooms?' beeinflusst werden, wobei das soweit ich mich erinnere noch nicht richtig geht, also das "nicht gruppieren". Und grundsätzliche war das nur so ein Schnellschuss ohne groß drüber nachzudenken, weil wenn man das braucht unter bestimmten Umständen, dann braucht man eigentlich auch eine Liste von Räumen die nicht gruppiert werden sollen oder andersrum.
Anwendungsfall war Lautsprecher in verschiedenen Stockwerken, wenn die gruppiert werden, dann ist es doof weil wenn jemand in dem einen Stockwerk die Wiedergabe stoppt oder was anderes abspielen will dann betrifft das auch das andere Stockwerk.
Gruppieren steht hier immer für Zone bilden, sollte man vielleicht umbenennen...
