### ISSUE TITLE
Ist der Source aktuell?

### ISSUE THREAD

**Issue by ChriD** [Alex9779/node-red-contrib-raumfeld#4]
Hi, ist der Source hier auf dem git aktuell?
Ich frage weil z.B. der "load playlist" node nicht funktioniert und ich ein paar nodes hinzufügen bzw. erweitern würde

**Comment by Alex9779** [comment]
Hi,
ja ist er, ich bin bisher nicht dazu gekommen weiter zu entwickeln und wegen anderen Problemen nutze ich es im Moment auch nicht. Pläne habe ich zwar aber keine Zeit...

**Comment by ChriD** [comment]
Passt. Danke für die Info!

**Comment by Alex9779** [comment]
Kein Problem, wobei ich eh eher unglücklich bin mit der Struktur und den vielen nodes.
Am Anfang stand ich vor der Entscheidung für jede Aktion ein node oder ein node und ne Auswahl der Aktion, hatte mich dann zunächst für ein node pro Aktion entschieden, ist aber dann entartet und es sind jetzt ziemlich viele...
Keine Ahnung, was da besser ist, node-red gibt ja beides her und wenn ich so andere anschaue ist das auch nicht wirklich durchgängig, ich finde die Auswahl halt recht schwierig wenn da zu viele Nodes drin stehen und ein Block dann auch noch soviele bereitstellt...

**Comment by ChriD** [comment]
Ja ist irgendwie schwer zu entscheiden. Aber nur eine node wär meiner Meinung nach zu wenig, die wird dann von der Programmierung her unübersichtlich. 
Ich mach einfach mal ein bisschen was und du kannst ja dann entscheiden ob du es reinmerged oder nicht

**Comment by Alex9779** [comment]
Klar, mach einfach mal.
Hab in den develop letztens ja was gemergt von jemand anderes, bin aber auch hier nicht dazu gekommen das zu prüfen.
