### ISSUE TITLE
How to setup first node?

### ISSUE THREAD

**Issue by gahujipo** [Alex9779/node-red-contrib-raumfeld#8]
I struggle with setting up this node. What do I have to specify in the field "Raumkernel"? The validator seems to validate for an IP address. So I specified the IP address where Node-Raumserver runs. Under the same ip it runs as docker container under port 8585 and as standard application under port 8080. No messages arrive when testing a few different events: play/pause, mute/unmute, volume change.

**Comment by Alex9779** [comment]
The raumkernel needs the IP of your Raumfeld host, I think if you use 0.0.0.0 it tries to discover your host but I am not absolutely sure this works...

**Comment by gahujipo** [comment]
Now I see how this works. I tried to enter the IP address of the speaker which hosts the controller. I can't use the bonjour discovery because my node-red runs in a container. But entering the host speaker's ip address doesn't work either. Is there implemented some logging where I can see the output of the raumkernel?

**Comment by Alex9779** [comment]
Hmmm strange, no unfortunately there is no logging...
I will have a look into it...
