### ISSUE TITLE
favorite load does not work

### ISSUE THREAD

**Issue by Falfango** [Alex9779/node-red-contrib-raumfeld#9]
Hi! 
I like your nodes, but I've an issue with the "load-favorite". It always plays the same favorite and do not change, if I request a different favorite. This is independend if I send the new favorite by msg.payload or put it directly in the node configuration.

**Comment by Alex9779** [comment]
I am sorry, I tested everything that came to my mind, favorites of type "radio station", "song", "playlist", "album" and "arstist" setting in the node or in the payload and it always switched to that favorite.
